FROM amazoncorretto:17.0.3-alpine
VOLUME /tmp
EXPOSE 9090
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} application.jar

ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_NAME=${DB_NAME}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV SERVER_PORT=${SERVER_PORT}

ENTRYPOINT ["java","-jar","/application.jar"]