version: '3'
services:
  # MySQL Database Service
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: thankgod
      MYSQL_DATABASE: bookdb
      MYSQL_USER: root
      MYSQL_PASSWORD: thankgod
    ports:
      - "3306:3306"
    networks:
      - book_system_network

  # Spring Boot Application Service
  spring-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: book_system_app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: thankgod
    networks:
      - book_system_network

networks:
  book_system_network: