spring:
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${HOST_NAME}:${PORT}/${DB_NAME}
    username: ${USERNAME}
    password: ${PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql

server:
  port:
    9090